### PR TITLE
To band return str

### PR DESCRIPTION
**Pull request by jsetty**
Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

Could not check any of the boxes above as there is no commit message style in the guidelines and no test suite.

Issue #138 

Thank you!

### CODE REVIEW

**Comment by remi-braun** [comment]
Hi !
Thanks to this proposal 😄 

I'd prefer to change the output type only if a keyword is added (i.e. `as_list` defaulting to True)
This behaviour should be also replicated to the `to_str` function, to keep it symmetric.

**Comment by remi-braun** [comment]
Thanks!
Could you now add a line in `CHANGES.md` with a small text and a reference to this PR ? (see other lines to get inspiration)
Don't hesitate to cite yourself 😉

**Comment by jsetty** [comment]
Suggested changes made and added the changes to CHANGES.md. Sorry for the mess!

**Comment by remi-braun** [comment]
Nice! Can I merge?

**Pull request merged**
