### PR TITLE
FIX: PNEO Regex

### PR DESCRIPTION
**Pull request by guillemc23**
* Fixed Pleiades NEO regex. I reordered the groups in the PNEO Product regex since it only catches the first occurence. I did the same in the manifest and also corrected the part related to the uuid, as it should use hyphens instead of downscores, plus, uuid always groups in 8-4-4-4-12

### CODE REVIEW

**Comment by remi-braun** [comment]
Thanks !
I see you also work with a lot of different sensors haha

**Comment by guillemc23** [comment]
@remi-braun kinda, yeah 😄

**Comment by remi-braun** [comment]
I have a PNEO with `DIM_PNEO3_202201182152117_PMS_ORT_PWOI_000007338_1_1_F_1.XML` DIMAP file, which fails with this new regex. I'll alter your solution accordingly :)

**Comment by guillemc23** [comment]
Hey @remi-braun ! Mine is `DIM_PNEO4_202303020837549_PMS-FS_ORT_91a0d2f7-bf97-4436-c479-d662e8760420.XML`, in case you wanna check both cases

**Comment by remi-braun** [comment]
I put the two usecases: `Constellation.PNEO: r"DIM_PNEO\d_\d{15}_(PMS-FS|MS-FS|PMS|MS|P)_(SEN|PRJ|ORT|MOS)_.{8,}(-.{4,}-.{4,}-.{4,}-.{12,}|_._._._.)\.XML",`

**Comment by guillemc23** [comment]
Nice one, thank you! And sorry for changing it in the first place, I thought it was just incomplete, not expecting to have more variations. According to their user manual, that last field corresponds to the job ID, and mine looked like an uuid, so I thought the job ID was always an uuid 😄 

There's also some cases that are not handled by this regex but I don't have any products to test, so I just didn't check. These are spectral processing `PAN`, `PMS-N` and `PMS-X`

**Comment by remi-braun** [comment]
Same here, that's why regexes may be broken for cases I just read about 🤷‍♂️

**Pull request merged**
