### PR TITLE
change preview in S2_product from TCI to PVI

### PR DESCRIPTION
**Pull request by floriandeboissieu**
See #84 for details

### Your checklist for this pull request
Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Check the commit's or even all commits' message styles matches our requested structure.
- [ ] Check your code additions will fail neither code linting checks nor unit test.

### Description
Please describe your pull request.

### Further comments
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

Thank you!

### CODE REVIEW

**Comment by remi-braun** [comment]
Thanks, this look good 🙏

**Comment by remi-braun** [comment]
I am doing all the testing on Gitlab, so I will add what's needed, thanks a lot!

**Comment by floriandeboissieu** [comment]
You're welcome!

**Comment by remi-braun** [comment]
@floriandeboissieu 0.19.4 has been uploaded to conda-forge, you'll be able to access it in a few minutes/hours 😉

**Comment by floriandeboissieu** [comment]
Thanks!

**Pull request merged**
